"""Console entry point for Dungeon Agents (Milestone 1).

Runs an interactive loop: the player types an action, the Game Master responds
with a short scene and 2-3 choices. Type `exit` (or `quit`) to leave.

Design notes:
- All I/O lives here; the agent itself lives in `agents/game_master.py`. That
  separation keeps the agent testable without a running console.
- We keep the running conversation so the Game Master has context across turns.
  The SDK's `Runner.run_sync(...).to_input_list()` gives us the accumulated
  history to feed back into the next turn.
"""

from __future__ import annotations

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel

from dungeon_agents.agents.game_master import build_game_master
from dungeon_agents.config import load_settings

EXIT_WORDS = {"exit", "quit"}
HELP_WORDS = {"help", "?", "/help"}
OPENING_PROMPT = "Begin the adventure. Set an opening scene and offer me my first choices."

# Player-facing help. Written to set honest expectations for the current
# milestone: the tools work, but deep mechanics (real attributes, rules, a goal)
# arrive in later milestones. Keeping this accurate avoids over-promising.
# NOTE: ASCII only — Windows' default console encoding (cp1252) can't render
# curly quotes, em dashes, or arrows, and Rich raises on them. Keep it portable.
HELP_TEXT = """\
[bold]How to play[/bold]

This is a [bold]free-text[/bold] adventure. On your turn you can:
- Type an [bold]action in your own words[/bold] - e.g. "I search the room",
  "I attack the goblin with my sword", "I try to bribe the guard".
- Or just type the [bold]number[/bold] of one of the choices the Game Master
  offers. Both work - you are never limited to the listed options.

[bold]Commands[/bold] (type these at any time)
- [cyan]help[/cyan]  - show this help
- [cyan]save[/cyan]  - ask the Game Master to save your progress
- [cyan]load[/cyan]  - resume a previously saved game
- [cyan]exit[/cyan]  - quit the game

[bold]About the dice[/bold]
When an action's outcome depends on chance (a risky attack, a tricky climb), the
Game Master rolls a real die behind the scenes - you'll see a
[dim][tool] roll_dice -> ...[/dim] line. The number is generated by real, tested
code, never made up by the AI.

[bold]A note on the character sheet[/bold]
Any attributes the story shows right now (hp, gold, reputation...) are narrative
flavour the storyteller improvises - they are not yet enforced by game rules.
Real, rule-backed attributes, inventory, and a proper goal to complete the game
are coming in later milestones. For now, enjoy the open-ended storytelling.
"""

console = Console()


def _print_scene(text: str) -> None:
    """Render a Game Master reply as Markdown inside a titled panel."""
    console.print(Panel(Markdown(text), title="Game Master", border_style="magenta"))


def _print_help() -> None:
    """Show the player-facing help panel."""
    console.print(Panel(HELP_TEXT, title="Help", border_style="yellow"))


def _build_tool_hooks():
    """Build run hooks that surface each tool call in the console.

    The tools run *inside* the SDK's turn, so by default the player only sees the
    narrated result — never the mechanic. Hooks are the SDK's official
    observability seam: the runtime calls `on_tool_start`/`on_tool_end` around
    each tool. We use them to print a dim line like "🎲 roll_dice → Rolled a 8…".
    This keeps the game logic untouched (observability, not behavior change) — the
    same audit-the-agent pattern we'll want in TestOps AI.

    Built lazily inside a function so importing this module never requires the SDK.
    """
    from agents import RunHooks

    class ToolActivityHooks(RunHooks):
        # Plain ASCII markers on purpose: Windows' default console encoding
        # (cp1252) can't encode emoji, and a raised UnicodeEncodeError inside a
        # hook aborts the whole tool call. Keep observability output portable.
        async def on_tool_start(self, context, agent, tool) -> None:
            console.print(f"[dim][tool] calling [bold]{tool.name}[/bold]…[/dim]")

        async def on_tool_end(self, context, agent, tool, result) -> None:
            console.print(f"[dim][tool] {tool.name} -> {result}[/dim]")

    return ToolActivityHooks()


def run() -> None:
    """Run the interactive game loop until the player exits."""
    settings = load_settings()

    if not settings.has_api_key:
        console.print(
            f"[bold red]No {settings.api_key_env_name} found.[/bold red] "
            f"(provider: [cyan]{settings.provider}[/cyan]) "
            "Copy [cyan].env.example[/cyan] to [cyan].env[/cyan] and add your key, "
            "then run again."
        )
        return

    # The SDK import is heavy (several seconds on first run) and blocks silently.
    # Show a status so the console doesn't look frozen — otherwise the first
    # launch feels like a hang. Imported lazily so the "no key" message above
    # never trips over a missing SDK.
    with console.status("[dim]Loading the game engine (first run can take a moment)…[/dim]"):
        from agents import Runner

        game_master = build_game_master(settings)
        tool_hooks = _build_tool_hooks()

    console.print(
        Panel(
            "[bold]Dungeon Agents[/bold]  -  a free-text fantasy adventure\n"
            "Type [cyan]help[/cyan] for how to play, or [cyan]exit[/cyan] to quit.\n"
            f"[dim]{settings.provider} - {settings.model}[/dim]",
            border_style="green",
        )
    )
    # Show the full how-to-play once up front so a new player isn't lost.
    _print_help()

    # The conversation history fed into each turn. Starts with the opening prompt.
    conversation: list = [{"role": "user", "content": OPENING_PROMPT}]

    while True:
        result = Runner.run_sync(game_master, conversation, hooks=tool_hooks)
        _print_scene(result.final_output)
        # Carry the full history forward so the next turn keeps context.
        conversation = result.to_input_list()

        try:
            # The label hints that free-form actions are allowed, not just the
            # numbered choices the Game Master lists.
            player_input = console.input(
                "[bold cyan]You[/bold cyan] [dim](an action or a choice #)[/dim]: "
            ).strip()
        except (EOFError, KeyboardInterrupt):
            console.print("\n[dim]Farewell, adventurer.[/dim]")
            return

        if player_input.lower() in EXIT_WORDS:
            console.print("[dim]Farewell, adventurer.[/dim]")
            return
        if player_input.lower() in HELP_WORDS:
            # Help is a meta-command: show it without spending a game turn.
            _print_help()
            continue
        if not player_input:
            continue

        conversation.append({"role": "user", "content": player_input})


def main() -> None:
    """Console-script entry point (see pyproject `[project.scripts]`)."""
    run()


if __name__ == "__main__":
    main()
