"""Console entry point for Dungeon Agents (Milestone 1).

Runs an interactive loop: the player types an action, the Game Master responds
with a short scene and 2-3 choices. Type `exit` (or `quit`) to leave.

Design notes:
- All I/O lives here; the agent itself lives in `agents/game_master.py`. That
  separation keeps the agent testable without a running console.
- We keep the running conversation so the Game Master has context across turns.
  The SDK's `Runner.run_sync(...).to_input_list()` gives us the accumulated
  history to feed back into the next turn.
"""

from __future__ import annotations

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel

from dungeon_agents.agents.game_master import build_game_master
from dungeon_agents.config import load_settings
from dungeon_agents.domain import state as game_state

EXIT_WORDS = {"exit", "quit"}
HELP_WORDS = {"help", "?", "/help"}
NEW_WORDS = {"new", "/new"}
STATS_WORDS = {"stats", "status", "/stats"}
INVENTORY_WORDS = {"inventory", "inv", "/inventory"}
SUMMARY_WORDS = {"summary", "recap", "/summary"}
DEBUG_WORDS = {"debug", "/debug"}
# save/load take an argument ("save battle"), so they are matched by first word.
SAVE_WORDS = {"save", "/save"}
LOAD_WORDS = {"load", "/load"}
SAVES_WORDS = {"saves", "/saves"}  # list named checkpoints
OPENING_PROMPT = "Begin the adventure. Set an opening scene and offer me my first choices."
RESUME_PROMPT = (
    "The player is resuming a saved game. Continue the adventure naturally from "
    "the scene just shown; do not restart or re-introduce the setting."
)

# The Critic reviews each scene before the player sees it. If it finds a
# contradiction with the tracked state, the Game Master is asked to regenerate.
# This cap is a deterministic anti-loop guard: we retry AT MOST this many times,
# then show the scene anyway (with a debug note). The limit lives in code, never
# at the model's discretion — an agent that keeps rejecting must not hang the game.
MAX_SCENE_RETRIES = 1

# Player-facing help. Written to set honest expectations for the current
# milestone: the tools work, but deep mechanics (real attributes, rules, a goal)
# arrive in later milestones. Keeping this accurate avoids over-promising.
# NOTE: ASCII only — Windows' default console encoding (cp1252) can't render
# curly quotes, em dashes, or arrows, and Rich raises on them. Keep it portable.
HELP_TEXT = """\
[bold]How to play[/bold]

This is a [bold]free-text[/bold] adventure. On your turn you can:
- Type an [bold]action in your own words[/bold] - e.g. "I search the room",
  "I attack the goblin with my sword", "I try to bribe the guard".
- Or just type the [bold]number[/bold] of one of the choices the Game Master
  offers. Both work - you are never limited to the listed options.

[bold]Commands[/bold] (type these at any time)
- [cyan]stats[/cyan]       - show your HP, gold, location and quest (exact, from the game state)
- [cyan]inventory[/cyan]   - show what you're carrying
- [cyan]summary[/cyan]     - show a recap of the story so far
- [cyan]help[/cyan]        - show this help (then re-shows your current scene)
- [cyan]save <name>[/cyan] - save a named checkpoint you can return to exactly
- [cyan]load <name>[/cyan] - restore a named checkpoint (state and story)
- [cyan]saves[/cyan]       - list your named checkpoints
- [cyan]new[/cyan]         - discard your game and start fresh (asks to confirm)
- [cyan]debug[/cyan]       - toggle debug mode (see the tools/agents at work under the hood)
- [cyan]exit[/cyan]        - quit the game (your progress is saved as you play)

Your progress is saved automatically as you play - you never lose your place.
When you start the game with a saved adventure, it asks whether to continue it or
start fresh, and continuing resumes exactly where you left off. Use [cyan]save
<name>[/cyan] to bookmark a specific moment you can [cyan]load[/cyan] later.

[bold]Your character, inventory and gold[/bold]
Your character now has real, rule-backed stats. Try things like:
- "I pick up the two torches" / "I use a health potion" - manage your
  [bold]inventory[/bold]. You can't use or drop an item you don't have.
- "I buy the rope for 5 gold" - spend [bold]gold[/bold]. You can't spend more
  than you carry; the game will tell you so.
- Taking damage lowers your [bold]HP[/bold]; it can't drop below 0 or rise above
  your maximum. These limits are enforced by tested code, not improvised.

[bold]About the dice[/bold]
When an action's outcome depends on chance (a risky attack, a tricky climb), the
Game Master rolls a real die behind the scenes - you'll see a
[dim][tool] roll_dice -> ...[/dim] line. The number is generated by real, tested
code, never made up by the AI. Watch for [dim][tool] ...[/dim] lines whenever a
rule (inventory, gold, HP) is applied.

[bold]Your quest, and how the game ends[/bold]
You have an active [bold]quest[/bold] - an objective to pursue. The adventure is
not endless:
- [bold]Win[/bold] by completing your quest (e.g. "I finish the quest" once
  you've done what it asks).
- [bold]Lose[/bold] if your HP reaches 0 and your character falls.
Ask the Game Master about your current quest any time.
"""

console = Console()


def _print_scene(text: str) -> None:
    """Render a Game Master reply as Markdown inside a titled panel."""
    console.print(Panel(Markdown(text), title="Game Master", border_style="magenta"))


def _print_status(*, inventory_only: bool = False) -> None:
    """Print the player's stats and/or inventory, read from the saved state.

    Deterministic on purpose: this reads the validated GameState directly rather
    than asking the Game Master to narrate it, so the numbers are always exact
    and consistent (never improvised by the model). If there's no save yet,
    there's nothing to show — say so plainly.
    """
    from dungeon_agents.domain import rules

    state = game_state.load_state_or_none()
    if state is None:
        console.print("[dim]No character yet - take an action to begin.[/dim]")
        return

    if not inventory_only:
        p = state.player
        quest = state.active_quest.title if state.active_quest else "not set yet"
        done = " (completed)" if state.active_quest and state.active_quest.completed else ""
        # A brand-new game starts with a neutral "unknown" location until the
        # Game Master's first scene sets it; show that gently.
        where = state.location if state.location != "unknown" else "not set yet"
        lines = [
            f"[bold]{p.name}[/bold]",
            f"HP:    {p.hp}/{p.max_hp}",
            f"Gold:  {p.gold}",
            f"Where: {where}",
            f"Quest: {quest}{done}",
        ]
        console.print(Panel("\n".join(lines), title="Stats", border_style="blue"))

    # get_inventory returns a ready-made, deterministic summary (from M4 rules).
    console.print(Panel(rules.get_inventory(state), title="Inventory", border_style="blue"))


def _print_summary() -> None:
    """Print the running story summary, read from the saved state.

    Deterministic: shows the `session_summary` the Game Master has been keeping,
    verbatim — not a freshly improvised recap. Empty early on, before anything
    story-significant has happened.
    """
    state = game_state.load_state_or_none()
    if state is None:
        console.print("[dim]No adventure yet - take an action to begin.[/dim]")
        return
    text = state.session_summary or "Nothing notable has happened yet."
    console.print(Panel(text, title="Story so far", border_style="cyan"))


def _start_new_game() -> None:
    """Seed and save a fresh starter GameState.

    Writing the starter state to disk immediately (rather than waiting for the
    first tool call to create it) means stats/inventory always have something to
    show from turn 0 — no "no character yet". Reuses the tools layer's
    `new_game_state()` so the starter hero/quest stay defined in one place.
    """
    from dungeon_agents.tools.game_tools import new_game_state

    game_state.save_state(new_game_state())


def _confirm(question: str) -> bool:
    """Ask a yes/no question at the console; default is No (safe for destructive ops).

    Returns True only on an explicit yes. EOF/Ctrl+C counts as No so an
    accidental interrupt never triggers a destructive action.
    """
    try:
        answer = console.input(f"[yellow]{question} [dim](y/N)[/dim]: [/yellow]").strip()
    except (EOFError, KeyboardInterrupt):
        return False
    return answer.lower() in {"y", "yes"}


def _save_checkpoint(name: str, conversation: list) -> None:
    """Save a named checkpoint (current state + conversation) from the console."""
    from dungeon_agents.domain.models import SaveSlot
    from dungeon_agents.domain.state import StateError

    state = game_state.load_state_or_none()
    if state is None:
        console.print("[dim]Nothing to save yet - take an action first.[/dim]")
        return
    try:
        slot = SaveSlot(name=name, state=state, conversation=conversation)
        msg = game_state.save_checkpoint(slot)
    except StateError as exc:
        console.print(f"[red]{exc}[/red]")
        return
    console.print(f"[dim]{msg}[/dim]")


def _list_checkpoints() -> None:
    """Print the names of saved checkpoints, or a note if there are none."""
    names = game_state.list_checkpoints()
    if not names:
        console.print("[dim]No saved checkpoints yet. Use [cyan]save <name>[/cyan].[/dim]")
        return
    listed = "\n".join(f"- {n}" for n in names)
    console.print(Panel(listed, title="Saved checkpoints", border_style="blue"))


def _remember_last_scene(scene: str) -> None:
    """Persist the Game Master's latest scene into the saved state (best-effort).

    Stored so a resumed game can reprint the exact scene the player was on — the
    deterministic resume from M5. Best-effort: if there's no valid save yet
    (nothing to attach the scene to), we skip silently; the next in-game save
    will capture state going forward.
    """
    current = game_state.load_state_or_none()
    if current is None:
        return
    current.last_scene = scene
    game_state.save_state(current)


def _check_end_of_game(state=None):
    """Return an end-of-game outcome from the validated state, or None.

    Deterministic: victory and defeat are decided by tested rules over the
    GameState (`is_game_won` / `is_game_over`), never by the narrator. The Game
    Master may describe a dramatic fall, but whether the game is actually OVER is
    read from the tracked HP and quest — the last and clearest application of the
    project's core rule that outcomes live in code, not in the story.

    Args:
        state: The GameState to judge. Defaults to the saved state (what the game
            loop uses); tests inject one directly for deterministic checks.

    Returns one of "won", "lost", or None (game continues). "lost" takes
    precedence: a fallen hero can't also have just won.
    """
    from dungeon_agents.domain import rules

    if state is None:
        state = game_state.load_state_or_none()
    if state is None:
        return None
    if rules.is_game_over(state):
        return "lost"
    if rules.is_game_won(state):
        return "won"
    return None


def _print_end_of_game(outcome: str) -> None:
    """Print the win/lose panel that ends the adventure."""
    if outcome == "won":
        console.print(
            Panel(
                "[bold]Victory![/bold] You have completed your quest. "
                "Your adventure ends in triumph.",
                title="The End",
                border_style="green",
            )
        )
    else:  # "lost"
        console.print(
            Panel(
                "[bold]You have fallen.[/bold] Your HP reached 0 and your "
                "adventure ends here.",
                title="Game Over",
                border_style="red",
            )
        )
    console.print(
        "[dim]Type [cyan]new[/cyan] next time to begin a fresh adventure.[/dim]"
    )


def _state_for_review() -> str:
    """Build a compact, factual snapshot of the tracked state for the Critic.

    Deterministic: read straight from the validated GameState so the Critic checks
    the scene against hard facts, not the model's memory. Empty-safe when there's
    no save yet.
    """
    from dungeon_agents.domain import rules

    state = game_state.load_state_or_none()
    if state is None:
        return "No tracked state yet."
    p = state.player
    quest = state.active_quest.title if state.active_quest else "none"
    where = state.location if state.location != "unknown" else "unset"
    return (
        f"HP: {p.hp}/{p.max_hp}; Gold: {p.gold}; Location: {where}; "
        f"Quest: {quest}. {rules.get_inventory(state)}"
    )


def _review_scene(critic, runner, scene: str, debug: DebugState) -> str | None:
    """Ask the Critic whether `scene` is consistent with the tracked state.

    Returns None if consistent (OK), or a short reason string if the Critic found
    a contradiction. The Critic's verdict is a STRUCTURED token ("OK" / "PROBLEM:
    ...") so this code — not another model — decides what to do next.
    """
    from dungeon_agents.agents.critic import CRITIC_PROBLEM_PREFIX

    review_input = [
        {
            "role": "user",
            "content": (
                "Tracked game state:\n"
                f"{_state_for_review()}\n\n"
                "Scene the Game Master just wrote:\n"
                f"{scene}\n\n"
                "Is the scene consistent with the tracked state? Answer OK or "
                "PROBLEM: <reason>."
            ),
        }
    ]
    verdict = runner.run_sync(critic, review_input).final_output.strip()
    if debug.enabled:
        console.print(f"[dim][debug] Critic verdict: {verdict}[/dim]")
    if verdict.upper().startswith(CRITIC_PROBLEM_PREFIX):
        return verdict[len(CRITIC_PROBLEM_PREFIX):].strip() or "unspecified contradiction"
    return None


def _review_character(character_judge, runner, scene: str, debug: DebugState) -> str | None:
    """Ask the Character Judge whether `scene` leaked the assistant's nature.

    The output-side safety check (M7): returns None if the scene stays in
    character, or a short reason if it broke character / leaked its prompt. Like
    the Critic, its verdict is a structured token (IN_CHARACTER / LEAK) so code
    decides. Returns None when no judge is configured (no API key at build time).
    """
    if character_judge is None:
        return None
    from dungeon_agents.agents.character_judge import CHARACTER_LEAK

    verdict = runner.run_sync(character_judge, scene).final_output.strip().upper()
    if debug.enabled:
        console.print(f"[dim][debug] Character Judge verdict: {verdict}[/dim]")
    if verdict.startswith(CHARACTER_LEAK):
        return "the scene broke character or revealed the assistant's nature"
    return None


def _play_turn(game_master, critic, character_judge, runner, conversation, debug, tool_hooks):
    """Run ONE game turn: generate a scene, review it, show it, persist it.

    This is the model-driven part of a turn — the only place that calls the Game
    Master and the Critic. It is invoked for the opening scene and after a real
    player action, but NOT for meta-commands (stats/inventory/help/...), which are
    pure state reads and must never spend a model call or re-run the Critic.

    The Critic reviews the scene against the tracked state before the player sees
    it; on a contradiction the Game Master regenerates, bounded by
    MAX_SCENE_RETRIES so a stubborn Critic can never hang the turn.

    Returns (scene, next_conversation, outcome), where outcome is "won"/"lost" or
    None. The caller shows the end-of-game panel and stops when outcome is set.

    If an input guardrail trips (a prompt-injection attempt), the turn is REFUSED:
    the model never runs, an in-character notice is shown, and (None, conversation,
    None) is returned so the caller keeps the previous scene and state unchanged.
    """
    from agents.exceptions import InputGuardrailTripwireTriggered

    try:
        result = runner.run_sync(game_master, conversation, hooks=tool_hooks)
    except InputGuardrailTripwireTriggered:
        console.print(
            Panel(
                "The Game Master pauses, unmoved. Your attempt to bend the rules "
                "of reality has no effect here - describe an action your character "
                "takes instead.",
                title="Game Master",
                border_style="magenta",
            )
        )
        if debug.enabled:
            console.print("[dim][debug] input guardrail tripped: prompt injection blocked[/dim]")
        return None, conversation, None
    for _ in range(MAX_SCENE_RETRIES):
        # Two independent reviews of the scene before the player sees it:
        # the Critic checks COHERENCE with state, the Character Judge checks
        # SAFETY (no break of character / prompt leak). Either firing triggers a
        # regeneration, bounded by MAX_SCENE_RETRIES.
        problem = _review_scene(critic, runner, result.final_output, debug)
        if problem is None:
            problem = _review_character(character_judge, runner, result.final_output, debug)
        if problem is None:
            break  # scene is consistent and in character — show it
        if debug.enabled:
            console.print(f"[dim][debug] regenerating scene ({problem})[/dim]")
        # Feed the problem back and regenerate from the same context.
        retry_input = result.to_input_list() + [
            {
                "role": "user",
                "content": (
                    "A review flagged your last scene: "
                    f"{problem}. Rewrite the scene so it fits, staying fully in "
                    "character as the Game Master and keeping the same intent and "
                    "choices."
                ),
            }
        ]
        result = runner.run_sync(game_master, retry_input, hooks=tool_hooks)

    scene = result.final_output
    _print_scene(scene)
    _remember_last_scene(scene)  # persist for a deterministic resume
    # End-of-game is decided by tested rules over the validated state, not by the
    # narration. The caller announces it and stops when this is set.
    return scene, result.to_input_list(), _check_end_of_game()


def _resume_banner(state) -> None:
    """Print the deterministic recap + last scene when resuming a saved game."""
    p = state.player
    quest = state.active_quest.title if state.active_quest else "none"
    recap_lines = [
        f"[bold]Resuming your adventure[/bold] as [bold]{p.name}[/bold].",
        f"Location: {state.location}  |  HP: {p.hp}/{p.max_hp}  |  Gold: {p.gold}",
        f"Quest: {quest}",
    ]
    if state.session_summary:
        recap_lines.append(f"\nSo far: {state.session_summary}")
    console.print(Panel("\n".join(recap_lines), title="Recap", border_style="cyan"))
    if state.last_scene:
        # Reprint the exact scene the player left on, verbatim (deterministic).
        _print_scene(state.last_scene)


# ASCII-art title shown once at startup — the classic console-game splash. Kept
# ASCII-only (no box-drawing/Unicode) so Windows' cp1252 console never chokes on
# it, the same portability rule as the rest of our console output.
TITLE_BANNER = r"""
 ____                                        _                    _
|  _ \ _   _ _ __   __ _  ___  ___  _ __    / \   __ _  ___ _ __ | |_ ___
| | | | | | | '_ \ / _` |/ _ \/ _ \| '_ \  / _ \ / _` |/ _ \ '_ \| __/ __|
| |_| | |_| | | | | (_| |  __/ (_) | | | |/ ___ \ (_| |  __/ | | | |_\__ \
|____/ \__,_|_| |_|\__, |\___|\___/|_| |_/_/   \_\__, |\___|_| |_|\__|___/
                   |___/                         |___/
"""


def _print_banner() -> None:
    """Show the ASCII-art game title — the console-game splash at startup."""
    console.print(f"[bold magenta]{TITLE_BANNER}[/bold magenta]")


def _print_help() -> None:
    """Show the player-facing help panel."""
    console.print(Panel(HELP_TEXT, title="Help", border_style="yellow"))


class DebugState:
    """A tiny mutable holder for the debug flag.

    Mutable (not a bool) so the in-game `debug` command can toggle it at runtime
    and the already-built hooks see the change without rebuilding the agent.
    """

    def __init__(self, enabled: bool) -> None:
        self.enabled = enabled


def _build_tool_hooks(debug: DebugState):
    """Build run hooks that surface each tool call — only when debug is on.

    The tools run *inside* the SDK's turn, so by default the player only sees the
    narrated result, never the mechanic. Hooks are the SDK's official
    observability seam: the runtime calls `on_agent_start` / `on_tool_start` /
    `on_tool_end` around the agent's work. In debug mode we print which agent is
    acting, each tool call with its arguments, and how long it took — the "see the
    guts" view. Off by default so normal play stays clean. This is exactly the
    audit-the-agent observability we'll want in TestOps AI, and it scales to M6:
    when multiple agents collaborate, on_agent_start shows which one is working.

    Built lazily inside a function so importing this module never requires the SDK.
    """
    from time import perf_counter

    from agents import RunHooks

    # Plain ASCII only: Windows' cp1252 console can't encode emoji/fancy glyphs,
    # and a raised UnicodeEncodeError inside a hook aborts the whole tool call.
    class ToolActivityHooks(RunHooks):
        def __init__(self) -> None:
            self._started: dict[int, float] = {}

        async def on_agent_start(self, context, agent) -> None:
            if debug.enabled:
                console.print(f"[dim][debug] agent [bold]{agent.name}[/bold] is working…[/dim]")

        async def on_tool_start(self, context, agent, tool) -> None:
            if debug.enabled:
                self._started[id(tool)] = perf_counter()
                console.print(f"[dim][debug] {agent.name} -> tool [bold]{tool.name}[/bold]…[/dim]")

        async def on_tool_end(self, context, agent, tool, result) -> None:
            if debug.enabled:
                started = self._started.pop(id(tool), None)
                took = f" ({(perf_counter() - started) * 1000:.0f} ms)" if started else ""
                console.print(f"[dim][debug]   {tool.name} -> {result}{took}[/dim]")

    return ToolActivityHooks()


def run() -> None:
    """Run the interactive game loop until the player exits."""
    settings = load_settings()

    if not settings.has_api_key:
        console.print(
            f"[bold red]No {settings.api_key_env_name} found.[/bold red] "
            f"(provider: [cyan]{settings.provider}[/cyan]) "
            "Copy [cyan].env.example[/cyan] to [cyan].env[/cyan] and add your key, "
            "then run again."
        )
        return

    # The SDK import is heavy (several seconds on first run) and blocks silently.
    # Show a status so the console doesn't look frozen — otherwise the first
    # launch feels like a hang. Imported lazily so the "no key" message above
    # never trips over a missing SDK.
    with console.status("[dim]Loading the game engine (first run can take a moment)…[/dim]"):
        from agents import Runner

        from dungeon_agents.agents.character_judge import build_character_judge
        from dungeon_agents.agents.critic import build_critic

        game_master = build_game_master(settings)
        critic = build_critic(settings)
        # Output-side safety reviewer (M7): flags a scene that broke character or
        # leaked the assistant's nature, triggering a regeneration in _play_turn.
        character_judge = build_character_judge(settings)
        debug = DebugState(enabled=settings.debug)
        tool_hooks = _build_tool_hooks(debug)

    # ASCII-art title splash, then a compact welcome panel. The full how-to-play
    # is NOT shown automatically — the panel points to `help` for players who want
    # it, keeping the startup clean.
    _print_banner()
    debug_note = "  |  debug ON" if debug.enabled else ""
    console.print(
        Panel(
            "[bold]Dungeon Agents[/bold]  -  a free-text fantasy adventure\n"
            "Type [cyan]help[/cyan] for how to play, [cyan]new[/cyan] to start over, "
            "or [cyan]exit[/cyan] to quit.\n"
            f"[dim]{settings.provider} - {settings.model}{debug_note}[/dim]",
            border_style="green",
        )
    )

    # Startup choice. If a saved game exists, ask whether to continue it or start
    # a fresh one (starting fresh discards the current game, so we confirm first).
    # With no save, jump straight into a new adventure — no menu to slow down a
    # first-time player. `_last_scene` tracks what to re-show after a meta-command
    # so the player never loses their place.
    saved = game_state.load_state_or_none()
    resuming = False
    if saved is not None:
        console.print(
            Panel(
                "A saved adventure was found.\n"
                "Type [cyan]continue[/cyan] to resume it, or [cyan]new[/cyan] to "
                "start over.",
                title="Welcome back",
                border_style="green",
            )
        )
        choice = ""
        while choice not in {"continue", "c", "new", "n"}:
            try:
                choice = console.input(
                    "[bold cyan]Load saved game?[/bold cyan] [dim](continue/new)[/dim]: "
                ).strip().lower()
            except (EOFError, KeyboardInterrupt):
                console.print("\n[dim]Farewell, adventurer.[/dim]")
                return
        if choice in {"continue", "c"}:
            resuming = True

    if resuming:
        _resume_banner(saved)
        conversation: list = [{"role": "user", "content": RESUME_PROMPT}]
        _last_scene = saved.last_scene
    else:
        # Starting fresh: if there was a save, confirm before discarding it.
        if saved is not None and not _confirm(
            "Start a new adventure? Your current game will be lost."
        ):
            # Player backed out — resume the existing game instead of losing it.
            _resume_banner(saved)
            conversation = [{"role": "user", "content": RESUME_PROMPT}]
            _last_scene = saved.last_scene
        else:
            game_state.clear_state()  # discard the old game explicitly
            _start_new_game()
            conversation = [{"role": "user", "content": OPENING_PROMPT}]
            _last_scene = ""

    # Play the opening scene once, up front. From here on the loop only generates
    # a new scene in response to a real player ACTION — meta-commands (stats,
    # inventory, help, ...) are pure state reads that re-show the current scene
    # without spending a model call or re-running the Critic.
    _last_scene, conversation, outcome = _play_turn(
        game_master, critic, character_judge, Runner, conversation, debug, tool_hooks
    )
    if outcome is not None:
        _print_end_of_game(outcome)
        return

    while True:
        try:
            # The label hints that free-form actions are allowed, not just the
            # numbered choices the Game Master lists.
            player_input = console.input(
                "[bold cyan]You[/bold cyan] [dim](action, choice #, or help/new/exit)[/dim]: "
            ).strip()
        except (EOFError, KeyboardInterrupt):
            console.print("\n[dim]Farewell, adventurer.[/dim]")
            return

        if player_input.lower() in EXIT_WORDS:
            console.print("[dim]Farewell, adventurer.[/dim]")
            return
        if player_input.lower() in HELP_WORDS:
            # Meta-command: show help without spending a turn, then re-show the
            # current scene so the player can pick up exactly where they were.
            _print_help()
            if _last_scene:
                _print_scene(_last_scene)
            continue
        if player_input.lower() in NEW_WORDS:
            # Starting fresh discards the current game — confirm first.
            if not _confirm("Start a new adventure? Your current game will be lost."):
                console.print("[dim]Keeping your current adventure.[/dim]")
                if _last_scene:
                    _print_scene(_last_scene)
                continue
            # Reset to a seeded starter state (so stats/inventory work right away),
            # then play a fresh opening scene.
            game_state.clear_state()
            _start_new_game()
            console.print("[dim]Starting a new adventure...[/dim]")
            conversation = [{"role": "user", "content": OPENING_PROMPT}]
            _last_scene, conversation, outcome = _play_turn(
                game_master, critic, character_judge, Runner, conversation, debug, tool_hooks
            )
            if outcome is not None:
                _print_end_of_game(outcome)
                return
            continue
        if player_input.lower() in STATS_WORDS:
            # Meta-command: show deterministic stats, then re-show the scene.
            _print_status()
            if _last_scene:
                _print_scene(_last_scene)
            continue
        if player_input.lower() in INVENTORY_WORDS:
            _print_status(inventory_only=True)
            if _last_scene:
                _print_scene(_last_scene)
            continue
        if player_input.lower() in SUMMARY_WORDS:
            # Show the running story recap, then re-show the scene.
            _print_summary()
            if _last_scene:
                _print_scene(_last_scene)
            continue
        if player_input.lower() in DEBUG_WORDS:
            # Toggle the "see the guts" view at runtime, without a game turn.
            debug.enabled = not debug.enabled
            console.print(
                f"[dim]Debug mode {'ON' if debug.enabled else 'OFF'}.[/dim]"
            )
            continue
        # save/load take a name argument ("save battle"), so match on first word.
        first_word = player_input.split(maxsplit=1)[0].lower() if player_input else ""
        if first_word in SAVES_WORDS:
            # List named checkpoints, then re-show the scene.
            _list_checkpoints()
            if _last_scene:
                _print_scene(_last_scene)
            continue
        if first_word in SAVE_WORDS:
            # Save a named checkpoint: current state + conversation, restored exactly.
            parts = player_input.split(maxsplit=1)
            if len(parts) < 2 or not parts[1].strip():
                console.print("[dim]Usage: [cyan]save <name>[/cyan] (e.g. save battle).[/dim]")
            else:
                _save_checkpoint(parts[1].strip(), conversation)
            if _last_scene:
                _print_scene(_last_scene)
            continue
        if first_word in LOAD_WORDS:
            # Load a named checkpoint: restore state AND conversation exactly.
            parts = player_input.split(maxsplit=1)
            if len(parts) < 2 or not parts[1].strip():
                console.print("[dim]Usage: [cyan]load <name>[/cyan]. See [cyan]saves[/cyan].[/dim]")
                continue
            slot = game_state.load_checkpoint(parts[1].strip())
            if slot is None:
                console.print(
                    f"[dim]No checkpoint named '{parts[1].strip()}' "
                    "(or it was incompatible).[/dim]"
                )
                continue
            # Restore: make this checkpoint the current game and resume its exact
            # conversation, so the Game Master keeps its full memory.
            game_state.save_state(slot.state)
            conversation = slot.conversation or [{"role": "user", "content": RESUME_PROMPT}]
            _last_scene = slot.state.last_scene
            console.print(f"[dim]Loaded checkpoint '{slot.name}'.[/dim]")
            _resume_banner(slot.state)
            continue
        if not player_input:
            continue

        # A real action: add it to the history and play a turn (GM + Critic).
        # This is the ONLY place a player action triggers scene generation.
        conversation.append({"role": "user", "content": player_input})
        scene, next_conversation, outcome = _play_turn(
            game_master, critic, character_judge, Runner, conversation, debug, tool_hooks
        )
        if scene is None:
            # Turn refused by a guardrail (e.g. prompt injection). Drop the blocked
            # message so it never poisons the history, then re-show the current
            # scene so the player can pick up exactly where they were (same as a
            # meta-command). Nothing about the game state advanced.
            conversation.pop()
            if _last_scene:
                _print_scene(_last_scene)
            continue
        _last_scene, conversation = scene, next_conversation
        if outcome is not None:
            _print_end_of_game(outcome)
            return


def main() -> None:
    """Console-script entry point (see pyproject `[project.scripts]`)."""
    run()


if __name__ == "__main__":
    main()
